version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    environment:
      - PORT=5000
      - CORS_ORIGINS=http://localhost:8080
      - FLASK_ENV=development
    networks:
      - betteravenet

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:5000
    networks:
      - betteravenet

networks:
  betteravenet:
    driver: bridge
