version: '3.8'

services:

  backend:
    build: ./betterave-backend
    networks:
      mynet:
        ipv4_address: 172.16.0.2
      
    volumes:
      - ./betterave-backend:/app
      - ./database:/database
    ports: 
      - 5000:5000

  frontend:
    build: ./frontend
    networks:
      mynet:
        ipv4_address: 172.16.0.3
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/29
